services:
  backend:
    image: juanpb0727/bills_manager-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: juanpb0727/bills_manager-frontend:latest
    container_name: frontend
    ports:
      - "2480:2480"
    restart: always
